env:
  API_KEY: "${{ secrets.API_KEY }}"
  GITHUB_ACTOR: "${{ secrets.PACKAGE_ACTOR }}"
  GITHUB_TOKEN: "${{ secrets.PACKAGE_TOKEN }}"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '16'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Start test
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test

    - name: Create Jacoco report
      run: gradle jacocoTestReport

    - name: Upload coverage reports to Codacy
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh)

  formatting:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--replace"
          files: 'app/**/*.java'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          skipCommit: false

name: Java CI with Gradle
on: [push, pull_request_target]

permissions:
  contents: write
